repos:

- repo: local
  hooks:
    - id: linters
      name: linters
      entry: ./scripts/run_linters
      language: system
      types: [ python ]

    - id: tests
      name: tests
      entry: ./scripts/run_tests
      language: system
      types: [ python ]

    - id: format
      name: format
      entry: ./scripts/run_formatters
      language: system
      types: [ python ]
