repos:


- repo: local
  hooks:
    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [ python ]
      args: [
        --max-line-length=120,
        --exclude=venv
      ]
