site_name: FastAPI-RESTful-Extension
site_description: FastAPI-RESTful-Extension
site_url: https://maximshumilo.github.io/fastapi-restful-extension/

theme:
  name: 'material'
  features:
      - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition

repo_name: fastapi-restful-extension
repo_url: https://github.com/maximshumilo/fastapi-restful-extension

nav:
  - Description: 'index.md'
  - Installation: 'installation.md'
  - User Guide:
      - A Minimal API: 'user-guide/minimal-api.md'
      - Versions API: 'user-guide/versions.md'
      - Resourceful Routing: 'user-guide/resourceful.md'
      - Security: ''
  - Get Help: ''
  - Development: ''
  - Release Notes: ''

extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/maximshumilo/'
    - icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/in/maxim-shumilo-0bb78318a/'
    - icon: fontawesome/brands/telegram
      link: 'https://t.me/maximshumilo'