# This is a basic workflow to help you get started with Actions

name: Publish

on: [push]


# on:
#   push:
#    tags:        
#       - '*' 

jobs:
  pubish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Build package
        run: |
          pip install --upgrade pip
          pip install wheel setuptools
          python setup.py sdist bdist_wheel
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
